# Generated by Django 4.0.4 on 2022-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0005_remove_project_technologies_project_technologies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='technologies',
            name='company',
        ),
        migrations.AddField(
            model_name='technologies',
            name='company',
            field=models.ManyToManyField(to='basic_app.company'),
        ),
    ]
